package com.core.example.java9.features;

import java.util.Optional;

import org.junit.Test;
import static org.junit.Assert.*;


import org.junit.Test;

public class OptionalExampleTest {

// Generated by qodo Gen
  // optionalExample_01 prints "Value is present: Hello" when Optional contains a value
    @Test
    public void test_optionalExample_01_value_present() {
        OptionalExample example = new OptionalExample();
        example.optionalExample_01();
        // Expected output: "Value is present: Hello"
    }

    // optionalExample_01 prints "Value is not present" when Optional is empty
    @Test
    public void test_optionalExample_01_value_not_present() {
        Optional<String> optional = Optional.empty();
        optional.ifPresentOrElse(value -> System.out.println("Value is present: " + value), () -> System.out.println("Value is not present"));
        // Expected output: "Value is not present"
    }

}
